apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetrackingtool
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 080637545225.dkr.ecr.eu-central-1.amazonaws.com/timetrackingtool:latest
          ports:
            - containerPort: 80